# Generated by Django 6.0.1 on 2026-04-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум статус'),
        ),
    ]
