# Generated by Django 6.0.1 on 2026-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_collection_options_alter_collection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на плеер/видео'),
        ),
    ]
